name: olanfoto
favicon: null
layout_spectrum: 0.4892473
typography_spectrum: 0.6523297
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Prueba 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202020'
    - '#5C5C5C'
  brandStrength: 1
  lightness: 0.708954
  saturation: 0.2146609
  rhythmicContrast: 0.826579
purpose: []
