layout_spectrum: 0.7939068
typography_spectrum: 0.1455337710212916
color:
  saturation: 0.04843269707635045
  brandStrength: 0.8918709638528526
  lightness: 0.29316858970560133
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.2987385450396687
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Abimelec
  email: cuentas@olanfoto.com
  url: www.olanfoto.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/10205e23-500d-4ee1-9cba-bef558b701ce.png
name: olanfoto
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: 'Entre la lluvia y su mirada '
    id: 3f482132-3810-4d92-ac9c-65c409eb09fb
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/84959e52-019f-41a7-8bd9-e7488ae1385b.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: El Gran Viaje
description: de los sueños
purpose: []
